[build]
  base = "apps/web"
  command = "cd ../.. && npm install && cd apps/web && npm run build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 