[build]
  command = "cd apps/web && pnpm install && pnpm run build"
  publish = "apps/web/.next"
  base = "apps/web"

[build.environment]
  NEXT_PUBLIC_APP_URL = "https://talentprimer.netlify.app"
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "your-stripe-publishable-key"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"
  NEXT_PUBLIC_SUPABASE_URL = "your-supabase-project-url"
  STRIPE_SECRET_KEY = "your-stripe-secret-key"
  STRIPE_WEBHOOK_SECRET = "your-stripe-webhook-secret"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  PNPM_VERSION = "10.8.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 